Cron: 30 30 5 * * * #将在 每天的 5:30:30 开始登陆，并等待到6:00 开始Book，期间自己登陆图书馆预约系统会造成程序失效
Threads: 5 #每个账号开启5个并发线程
LogLevel: 1 #日志等级 暂时没啥用
User:
  - Username: "201900000001"
    Password: "qlu000001"
    BookList:
      - 1222
      - 1223
      - 1224
    InfoAPI:  #通知api 自行修改咯 示例：http://assdadas.das.d.d/das/asd?a={%msg%}&b=zhz
  - Username: "201900000002"
    Password: "qlu000005"
    BookList:
      - 3222
      - 3223
      - 3224
    InfoAPI: 