name: Build and Run Book on Windows

on:
  schedule:
    # Runs at 05:00 UTC every day
    - cron: '0 5 * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main ] # 每次向 main 分支推送时自动运行

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18' # Adjust this to match the Go version you use

    - name: Change to cmd directory
      run: |
        cd cmd
        dir # List files for debugging purposes

    - name: Build the Book executable
      run: |
        go build -o Book.exe
      working-directory: ./cmd

    - name: Run Book with config
      run: |
        .\Book.exe config.yml
      working-directory: ./cmd
